extends:
- standard
- prettier
- prettier/react
parser: babel-eslint
parserOptions:
  ecmaVersion: 8
  ecmaFeatures:
    experimentalObjectRestSpread: true
    impliedStrict: true
    classes: true
env:
  browser: true
  node: true
  jest: true
rules:
  no-unused-vars:
  - error
  - vars: local
    args: none
  prettier/prettier:
  - error
  - semi: false
    singleQuote: true
    printWidth: 120
plugins:
- prettier
